### ISSUE TITLE
Explaining use of offline analyzer

### ISSUE THREAD

**Issue by hongxuchen** [parasol-aser/UFO#3]
I'm trying ufo-predict, but got lost in how to use it correctly.

Suppose `ufo-trace_20131` is the trace directory generated by the online tracking procedure when tested on [test.cc](https://github.com/parasol-aser/UFO/blob/master/test.cc). The output of `java -jar ~/Downloads/runufo.jar` is like:
```
21:19:55.776 [main] INFO aser.ufo.Main - app_name test; trace_dir /home/hongxu/concurrency/UFO/test/ufo-trace_20131.
21:19:55.779 [main] INFO aser.ufo.Main - solver_timeout 120
21:19:55.779 [main] INFO aser.ufo.Main - solver_mem 2000
21:19:55.779 [main] INFO aser.ufo.Main - window_size 100000
java.lang.NumberFormatException: For input string: "ffffffffff600000"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Long.parseLong(Long.java:692)
        at aser.ufo.trace.EventLoader.loadCModuleInfo(EventLoader.java:156)
        at aser.ufo.trace.EventLoader.init(EventLoader.java:69)
        at aser.ufo.Session.init(Session.java:70)
        at aser.ufo.Main.main(Main.java:29)
21:19:55.806 [main] INFO aser.ufo.trace.EventLoader - tid: 0 Total Events:  67
21:19:55.806 [main] INFO aser.ufo.trace.EventLoader - tid: 1 Total Events:  22
Total loading time:  8ms
Total reachability analysis time:  2ms
Start Events: 1
Join Events: 1
Lock Events: 4
Unlock Events: 4
Wait/Notify Events: 2
Alloc Events: 7
DeAlloc Events: 9
Total Sync Events: 12
Total Alloc Events: 7
Total USE Events: 6
Total Free Events: 9
Total Read Events: 4
Total Write Events: 2
Total Events: 89
21:19:55.825 [main] INFO aser.ufo.Session - candidateUafLs: 1

------- #1 use call stack  
? pc: 0x4b6ad8
  /home/hongxu/LLVM/6.0.0/llvm/projects/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:882 pc: 0x449e5e

------- #0 free call stack  
/home/hongxu/LLVM/6.0.0/llvm/projects/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:624 pc: 0x44d0eb
  ? pc: 0x4b6bb9
    ? pc: 0x4b6ded

=================================

Session 1 | avg vals -1 | constr max 0  avg -1 | total constr 0 | total candidate UaF 0 
Solved UAF: {}
```

The result seems not expected since there supposed to be a UAF. To me, it seems that the solving procedure is not actually processed?

(There is a *minor* issue that there is a `[vsyscall]|ffffffffff600000|ffffffffff601000|` inside `_module_info.txt` which fails `Long.parseLong`.)

Another issue that confuses me is that [TracePreprocessor](https://github.com/parasol-aser/UFO/blob/master/ufo-predict/src/main/java/aser/ufo/TracePreprocessor.java) has a main entry. May I know how to use this?

I ran it with `<WRAPPER> /home/hongxu/concurrency/UFO/test/ufo-trace_20131 /home/hongxu/concurrency/UFO/test/out-ufo-trace`, and it throws an exception:
```
Creating: "/home/hongxu/concurrency/UFO/test/out-ufo-trace": true
Start to uncompress 5 trace files from /home/hongxu/concurrency/UFO/test/ufo-trace_20131
java.io.IOException: [/home/hongxu/concurrency/UFO/test/ufo-trace_20131/1] Could not read enough data, requested: 1191182336  actual: 264
	at aser.ufo.TracePreprocessor.unzipBlocks(TracePreprocessor.java:160)
	at aser.ufo.TracePreprocessor$1.call(TracePreprocessor.java:77)
	at aser.ufo.TracePreprocessor$1.call(TracePreprocessor.java:74)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
java.io.IOException: PARSING_ERROR(2)
	at org.xerial.snappy.SnappyNative.throw_error(SnappyNative.java:98)
	at org.xerial.snappy.SnappyNative.uncompressedLength(Native Method)
	at org.xerial.snappy.Snappy.uncompressedLength(Snappy.java:634)
	at aser.ufo.TracePreprocessor.unzipBlocks(TracePreprocessor.java:164)
	at aser.ufo.TracePreprocessor$1.call(TracePreprocessor.java:77)
	at aser.ufo.TracePreprocessor$1.call(TracePreprocessor.java:74)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Done: 883 (0.000842 MB) -> 46 (0.000044 MB). Rate: 1919.565217%
```
May I know what's going on?

**Comment by hongxuchen** [comment]
For the record, I will summarize the answer replied by Andrew in the email.

- `fast_detect` should be set to false in order to invoke the constraint solving.
- TracePreprocessor is not used for current version; it is used when the onling tracing data is compressed.
